In [3]:
import torch
import torch.nn as nn
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import torch.nn.functional as F
from torchvision import datasets, transforms
import numpy as np
from torch.utils.data import Dataset, DataLoader, random_split

In [4]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu') #choose whether to use gpu or cpu

In [5]:
data_dir = r'C:\Users\Public\PartIIB project 2023_2024\Image collection without reaction\00AgNO3_mole_fraction\Outputs_Grayscale_Labelled_Images_Sizes\size_folder'  #path to the folder containing the images
# data_dir = r'C:\Users\Public\PartIIB project 2023_2024\PastData\helical_size'



In [6]:
from torch.utils.data import Dataset
from torchvision import transforms
from PIL import Image
import os

class CustomImageDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.root_dir = root_dir
        self.transform = transform
        self.images = sorted(os.listdir(root_dir))
        self.labels = [self.extract_label(img) for img in self.images]

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_name = os.path.join(self.root_dir, self.images[idx])
        image = Image.open(img_name)

        if self.transform:
            image = self.transform(image)

        label = self.labels[idx]
        return image, label

    def extract_label(self, img_name):
        # Assuming that the label is part of the filename before the first underscore
        label = float(img_name[-17:-5]) #this is the right code, just commented out for testing purposes
        # label = img_name
        return label

# Example usage:
data_transform = transforms.Compose(
[transforms.ToTensor(),
transforms.Normalize((0.5), (0.5))]) 

custom_dataset = CustomImageDataset(root_dir=data_dir, transform=data_transform)

# # Accessing the data
# for img, label in custom_dataset:
#     print(f"Image shape: {img.shape}, Label: {label}")

print(len(custom_dataset))
# train_set, val_set, test_set = random_split(custom_dataset, [int(len(custom_dataset)*0.75), int(len(custom_dataset)*0.15), int(len(custom_dataset)*0.100056)]) #splits data into training, validation and test sets
train_set, test_set = random_split(custom_dataset, [int(len(custom_dataset)*0.75), int(len(custom_dataset)*0.25003)])
print(len(train_set))
# print(len(val_set))
print(len(test_set))

15800
11850
3950


In [9]:
#hyper parameters
num_epochs = 30
batch_size = 1
# learning_rate = 0.0005
learning_rate = 0.001

train = DataLoader(train_set, batch_size=batch_size, shuffle=True)
# val = DataLoader(val_set, batch_size=batch_size, shuffle=False)
test = DataLoader(test_set, batch_size=batch_size, shuffle=False)

class ConvNet(nn.Module): # note need to find out image size
    def __init__(self):
        super(ConvNet, self).__init__()
        self.conv1 = nn.Conv2d(1,8,10, padding='same') #in_channels, out_channels, kernel_size
        self.normalise1 = nn.BatchNorm2d(8)
        # self.pool = nn.MaxPool2d(5,5) #kernel_size, stride (shift x pixel to the right)
        self.pool1 = nn.AvgPool2d(10, stride=10)
        self.conv2 = nn.Conv2d(8, 16, 10, padding='same')
        self.normalise2 = nn.BatchNorm2d(16)
        self.pool2 = nn.AvgPool2d(2, stride=2)
        self.conv3 = nn.Conv2d(16, 32, 10, padding='same')
        self.normalise3 = nn.BatchNorm2d(32) 
        self.conv4 = nn.Conv2d(32, 32, 10, padding='same')
        # self.fc1 = nn.Linear(16*3*3, 120) # 3x3 is the size of the image after 2 conv layers, 16 is the number of channels, 120 is the number of nodes in the hidden layer
        # self.fc2 = nn.Linear(120,84)
        # self.fc3 = nn.Linear(60, 1)
        self.fc = nn.Linear(32*5*5, 1)
        self.dropout = nn.Dropout(0.2)


    def forward(self, x):
        x = self.pool1(F.relu(self.normalise1(self.conv1(x)))) 
        x = self.pool2(F.relu(self.normalise2(self.conv2(x)))) 
        x = F.relu(self.normalise3(self.conv3(x)))
        x = F.relu(self.normalise3(self.conv4(x)))
        x = x.view(-1, 32*5*5)  #flatten
        # x = F.relu(self.fc1(x))
        # x = F.relu(self.fc2(x))
        x = self.fc(x)
        return x

model = ConvNet().to(device)

# loss and optimizer
# criterion = nn.CrossEntropyLoss()
criterion = nn.MSELoss()
# optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate, momentum = 0.9)
#training loop
n_total_steps = len(train)
for epoch in range(num_epochs):
    total_loss = 0
    for i, (images, labels) in enumerate(train):
        images = images.to(device)
        labels = labels.to(device)

        #forward
        outputs = model(images)
        print(labels)
        labels = labels.float() #this is the right code, just commented out for testing purposes
        # labels = float(labels[0][-17:-5])
        loss = criterion(outputs, labels)

        #backward
        optimizer.zero_grad()

        loss.backward()
        optimizer.step()

        # if (i+1) % 1000 ==0:
        print(f'epoch {epoch+1}/{num_epochs}, step {i+1}/{n_total_steps}, loss = {loss.item():.4f}')
        total_loss += loss.item()
    print(f'epoch {epoch+1}/{num_epochs}, average loss = {total_loss/len(train):.4f}')
            

print("Finished Training")

tensor([11.0702], dtype=torch.float64)
epoch 1/30, step 1/11850, loss = 118.7364
tensor([8.2909], dtype=torch.float64)
epoch 1/30, step 2/11850, loss = 0.4283
tensor([17.5096], dtype=torch.float64)
epoch 1/30, step 3/11850, loss = 25.6015
tensor([10.2574], dtype=torch.float64)
epoch 1/30, step 4/11850, loss = 173.0653
tensor([9.5975], dtype=torch.float64)
epoch 1/30, step 5/11850, loss = 41.1791
tensor([10.1065], dtype=torch.float64)
epoch 1/30, step 6/11850, loss = 29.9260
tensor([11.3893], dtype=torch.float64)
epoch 1/30, step 7/11850, loss = 101.0302
tensor([8.8615], dtype=torch.float64)
epoch 1/30, step 8/11850, loss = 12.6248
tensor([3.4739], dtype=torch.float64)
epoch 1/30, step 9/11850, loss = 72.7353
tensor([16.6058], dtype=torch.float64)
epoch 1/30, step 10/11850, loss = 12.9845
tensor([7.6848], dtype=torch.float64)
epoch 1/30, step 11/11850, loss = 7.2736
tensor([5.4679], dtype=torch.float64)
epoch 1/30, step 12/11850, loss = 70.0291
tensor([1.3468], dtype=torch.float64)
epoc

c:\Users\cs2036\AppData\Local\anaconda3\Lib\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


tensor([8.0108], dtype=torch.float64)
epoch 1/30, step 17/11850, loss = 37.6301
tensor([22.5012], dtype=torch.float64)
epoch 1/30, step 18/11850, loss = 13.6972
tensor([23.7414], dtype=torch.float64)
epoch 1/30, step 19/11850, loss = 0.7553
tensor([5.8884], dtype=torch.float64)
epoch 1/30, step 20/11850, loss = 523.9794
tensor([7.2561], dtype=torch.float64)
epoch 1/30, step 21/11850, loss = 191.1088
tensor([7.6314], dtype=torch.float64)
epoch 1/30, step 22/11850, loss = 0.1113
tensor([1.0617], dtype=torch.float64)
epoch 1/30, step 23/11850, loss = 0.6440
tensor([9.5071], dtype=torch.float64)
epoch 1/30, step 24/11850, loss = 86.4704
tensor([9.9311], dtype=torch.float64)
epoch 1/30, step 25/11850, loss = 90.6113
tensor([11.9114], dtype=torch.float64)
epoch 1/30, step 26/11850, loss = 135.7297
tensor([9.7371], dtype=torch.float64)
epoch 1/30, step 27/11850, loss = 89.1703
tensor([18.6993], dtype=torch.float64)
epoch 1/30, step 28/11850, loss = 336.9332
tensor([17.2831], dtype=torch.float

In [1]:
with torch.no_grad(): # no need to calculate gradient
    squared_difference = 0
    for images, labels in test:
        images = images.to(device)
        labels = labels.to(device)
        outputs = model(images)
        
        #value, index
        _, predictions = torch.max(outputs, 1)
        squared_difference += (predictions - labels) ** 2
    
    rmse = torch.sqrt(squared_difference / len(test))
    print(f'RMSE = {rmse}')

NameError: name 'torch' is not defined

In [ ]:
import time
from tqdm import tqdm

count =0
for i in tqdm(range(100)):
    count += 1
    time.sleep(1)
print(count)